### ISSUE TITLE
[HW] Steven Matison (WIP)

### ISSUE THREAD

**Issue by ds-steven-matison** [datastaxdevs/workshop-spring-stargate#11]
**Name:** Steven Matison
**Email:** steven.matison@datastax.com
**Linkedin Profile:** https://www.linkedin.com/in/steven-matison/

Attach the homework step I screenshots below:
-----------------------------------------

<img width="1792" alt="Screen Shot 2021-06-14 at 2 58 46 PM" src="https://user-images.githubusercontent.com/70520951/121955593-2782b800-cd2e-11eb-8005-cbb8951be183.png">
<img width="1792" alt="Screen Shot 2021-06-14 at 2 59 53 PM" src="https://user-images.githubusercontent.com/70520951/121955604-29e51200-cd2e-11eb-9205-019dece8e345.png">
<img width="1791" alt="Screen Shot 2021-06-14 at 3 01 53 PM" src="https://user-images.githubusercontent.com/70520951/121955614-2ce00280-cd2e-11eb-9a55-b97f3a1e30d1.png">
<img width="1792" alt="Screen Shot 2021-06-14 at 3 03 26 PM" src="https://user-images.githubusercontent.com/70520951/121955617-2fdaf300-cd2e-11eb-97f1-edab8f82faa4.png">
<img width="1791" alt="Screen Shot 2021-06-14 at 3 04 11 PM" src="https://user-images.githubusercontent.com/70520951/121955626-323d4d00-cd2e-11eb-822b-101faf8e9cc5.png">
<img width="1792" alt="Screen Shot 2021-06-14 at 3 04 26 PM" src="https://user-images.githubusercontent.com/70520951/121955636-349fa700-cd2e-11eb-9c83-cde392fe2ad0.png">
<img width="1791" alt="Screen Shot 2021-06-14 at 3 09 52 PM" src="https://user-images.githubusercontent.com/70520951/121955648-38332e00-cd2e-11eb-9815-803ae04e9ef8.png">

Blocked by GitPod IDE:
![Screen Shot 2021-06-14 at 3 11 12 PM](https://user-images.githubusercontent.com/70520951/121955656-3a958800-cd2e-11eb-8ea0-2ab64a3e265f.png)
<img width="1792" alt="Screen Shot 2021-06-14 at 3 21 46 PM" src="https://user-images.githubusercontent.com/70520951/121955669-3d907880-cd2e-11eb-91b6-c7dd42f33681.png">
<img width="1792" alt="Screen Shot 2021-06-14 at 3 24 03 PM" src="https://user-images.githubusercontent.com/70520951/121955682-408b6900-cd2e-11eb-9951-b686bc548b98.png">

Blocked by dependency error in Unit tests:

<img width="1792" alt="Screen Shot 2021-06-14 at 3 24 03 PM" src="https://user-images.githubusercontent.com/70520951/121955968-8fd19980-cd2e-11eb-836a-75b487cfaa59.png">

  
Attach the homework step II screenshots below:
-----------------------------------------

<img width="1772" alt="Screen Shot 2021-06-14 at 2 52 15 PM" src="https://user-images.githubusercontent.com/70520951/121944165-58f48700-cd20-11eb-8a27-370ce8910630.png">

**Comment by clun** [comment]
Blocked by dependency error in Unit tests:
> Repository is now fixed. You should be able to proceed,

**Comment by clun** [comment]
Great Job !

Here is you badge:
https://api.badgr.io/public/assertions/Ud_FVrQAQsK7DRIzmqO8uQ?identity__email=steven.matison%40datastax.com

**Comment by ds-steven-matison** [comment]
Ty Ty ty...  i did get an error in the SdkDevopsApi

```
stevenmatison@smatison-rmbp16 stargate-demo % mvn test -Dtest=com.datastax.demo.stargate.Ex4_SdkDevopsApi
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< com.datastax:stargate-demo >---------------------
[INFO] Building stargate-demo 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ stargate-demo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 99 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ stargate-demo ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ stargate-demo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/stevenmatison/Documents/GitHub/workshop-spring-stargate/stargate-demo/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ stargate-demo ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ stargate-demo ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.datastax.demo.stargate.Ex4_SdkDevopsApi
09:30:25,988 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
09:30:25,988 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
09:30:25,988 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/Users/stevenmatison/Documents/GitHub/workshop-spring-stargate/stargate-demo/target/classes/logback.xml]
09:30:25,989 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
09:30:25,989 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/Users/stevenmatison/Documents/GitHub/workshop-spring-stargate/stargate-demo/target/classes/logback.xml]
09:30:25,989 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/Users/stevenmatison/.m2/repository/com/datastax/stargate/stargate-sdk/0.1.10/stargate-sdk-0.1.10.jar!/logback.xml]
09:30:25,989 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/Users/stevenmatison/.m2/repository/com/datastax/astra/astra-sdk/0.1.10/astra-sdk-0.1.10.jar!/logback.xml]
09:30:26,035 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
09:30:26,036 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
09:30:26,040 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
09:30:26,043 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
09:30:26,074 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to WARN
09:30:26,074 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
09:30:26,075 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.datastax.demo] to INFO
09:30:26,075 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.datastax.astra] to INFO
09:30:26,075 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.datastax.stargate] to INFO
09:30:26,075 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.datastax.oss] to ERROR
09:30:26,075 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.junit.vintage] to ERROR
09:30:26,075 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
09:30:26,075 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@329dbdbf - Registering current configuration as safe fallback point

  _________ __                             __          
  /   _____//  |______ _______  _________ _/  |_  ____  
  \_____  \\   __\__  \\_  __ \/ ___\__  \\   __\/ __ \ 
  /        \|  |  / __ \|  | \/ /_/  > __ \|  | \  ___/ 
 /_______  /|__| (____  /__|  \___  (____  /__|  \___  >
        \/           \/     /_____/     \/          \/ 
 ________                         
 \______ \   ____   _____   ____  
  |    |  \_/ __ \ /     \ /  _ \ 
  |    `   \  ___/|  Y Y  (  <_> )
 /_______  /\___  >__|_|  /\____/ 
         \/     \/      \/        

 DataStax Developer Advocate team
        
09:30:26.516 INFO  com.datastax.demo.stargate.Ex4_SdkDevopsApi   : Starting Ex4_SdkDevopsApi on smatison-rmbp16 with PID 99087 (started by stevenmatison in /Users/stevenmatison/Documents/GitHub/workshop-spring-stargate/stargate-demo)
09:30:26.518 INFO  com.datastax.demo.stargate.Ex4_SdkDevopsApi   : No active profile set, falling back to default profiles: default
09:30:27.362 INFO  com.datastax.astra.sdk.AstraClient            : Initializing [AstraClient]
09:30:27.364 INFO  com.datastax.astra.sdk.AstraClient            : + Load configuration from file ~/.astrarc
09:30:27.365 INFO  com.datastax.astra.sdk.AstraClient            : + Load configuration from Environment Variables/Property
09:30:27.365 INFO  com.datastax.astra.sdk.AstraClient            : + Load configuration from Builder parameters
09:30:27.368 INFO  com.datastax.astra.sdk.AstraClient            : + Devops API is enabled.
09:30:27.368 INFO  com.datastax.astra.sdk.AstraClient            : + SecureBundle Path used: /Users/stevenmatison/.astra/secure_connect_bundle_60982f34-dd75-4113-b551-7eaf5e9d8a80.zip
09:30:27.369 INFO  com.datastax.astra.sdk.AstraClient            : + Using clientId/clientSecret for CqlSession
09:30:27.370 INFO  com.datastax.stargate.sdk.StargateClient      : Initializing [StargateClient]
09:30:27.486 INFO  com.datastax.stargate.sdk.doc.ApiDocumentClient : + Document API:  https://60982f34-dd75-4113-b551-7eaf5e9d8a80-us-east1.apps.astra.datastax.com/api/rest, 
09:30:27.486 INFO  com.datastax.stargate.sdk.rest.ApiRestClient  : + Rest API: https://60982f34-dd75-4113-b551-7eaf5e9d8a80-us-east1.apps.astra.datastax.com/api/rest, 
09:30:27.487 INFO  com.datastax.stargate.sdk.graphql.ApiGraphQLClient : + Rest API: http://localhost:8080, 
09:30:27.495 INFO  com.datastax.stargate.sdk.StargateClient      : Using Keyspace stargate
09:30:30.069 INFO  com.datastax.stargate.sdk.StargateClient      : + Cql API: Enabled
09:30:30.069 INFO  com.datastax.stargate.sdk.StargateClient      : [StargateClient] has been initialized
09:30:30.070 INFO  com.datastax.astra.sdk.AstraClient            : [AstraClient] has been initialized.
09:30:30.559 WARN  org.thymeleaf.templatemode.TemplateMode       : [THYMELEAF][main] Template Mode 'XHTML' is deprecated. Using Template Mode 'HTML' instead.
09:30:31.156 INFO  com.datastax.demo.stargate.Ex4_SdkDevopsApi   : Started Ex4_SdkDevopsApi in 4.837 seconds (JVM running for 5.635)
09:30:32.008 ERROR com.datastax.astra.sdk.databases.DatabasesClient : Error in 'findDatabases', params=databases?include=non_terminated&provider=all&limit=25
09:30:32.059 ERROR com.datastax.astra.sdk.databases.DatabasesClient : Cannot parse response 404 page not found

com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.datastax.astra.sdk.utils.ApiResponseError` (although at least one Creator exists): no int/Int-argument constructor/factory method to deserialize from Number value (404)
 at [Source: (String)"404 page not found
"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1455)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1081)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromInt(ValueInstantiator.java:262)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromInt(StdValueInstantiator.java:356)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromNumber(BeanDeserializerBase.java:1359)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:178)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3466)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
	at com.datastax.astra.sdk.utils.ApiDevopsSupport.processErrors(ApiDevopsSupport.java:80)
	at com.datastax.astra.sdk.databases.DatabasesClient.searchDatabases(DatabasesClient.java:165)
	at com.datastax.astra.sdk.databases.DatabasesClient.databasesNonTerminated(DatabasesClient.java:121)
	at com.datastax.demo.stargate.Ex4_SdkDevopsApi.listAvailableDatabases(Ex4_SdkDevopsApi.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.12 s <<< FAILURE! - in com.datastax.demo.stargate.Ex4_SdkDevopsApi
[ERROR] listAvailableDatabases  Time elapsed: 0.909 s  <<< ERROR!
java.lang.RuntimeException: 
Error code2=404 response=404 page not found

	at com.datastax.demo.stargate.Ex4_SdkDevopsApi.listAvailableDatabases(Ex4_SdkDevopsApi.java:18)

09:30:34.159 INFO  com.datastax.stargate.sdk.StargateClient      : Closing CqlSession.
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   Ex4_SdkDevopsApi.listAvailableDatabases:18 » Runtime Error code2=404 response=...
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[ERROR] There are test failures.

Please refer to /Users/stevenmatison/Documents/GitHub/workshop-spring-stargate/stargate-demo/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.146 s
[INFO] Finished at: 2021-06-15T09:30:34-04:00
[INFO] ------------------------------------------------------------------------
```
